// Code generated by MockGen. DO NOT EDIT.
// Source: contract\i-crypto.go

// Package contract is a generated GoMock package.
package contract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockICrypto is a mock of ICrypto interface.
type MockICrypto struct {
	ctrl     *gomock.Controller
	recorder *MockICryptoMockRecorder
}

// MockICryptoMockRecorder is the mock recorder for MockICrypto.
type MockICryptoMockRecorder struct {
	mock *MockICrypto
}

// NewMockICrypto creates a new mock instance.
func NewMockICrypto(ctrl *gomock.Controller) *MockICrypto {
	mock := &MockICrypto{ctrl: ctrl}
	mock.recorder = &MockICryptoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockICrypto) EXPECT() *MockICryptoMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockICrypto) Compare(arg0, arg1 []byte) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockICryptoMockRecorder) Compare(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockICrypto)(nil).Compare), arg0, arg1)
}

// Decrypt mocks base method.
func (m *MockICrypto) Decrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockICryptoMockRecorder) Decrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*MockICrypto)(nil).Decrypt), arg0)
}

// Encrypt mocks base method.
func (m *MockICrypto) Encrypt(arg0 []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encrypt", arg0)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encrypt indicates an expected call of Encrypt.
func (mr *MockICryptoMockRecorder) Encrypt(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encrypt", reflect.TypeOf((*MockICrypto)(nil).Encrypt), arg0)
}
