// Code generated by MockGen. DO NOT EDIT.
// Source: contract\i-file-path.go

// Package contract is a generated GoMock package.
package contract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIFilePath is a mock of IFilePath interface.
type MockIFilePath struct {
	ctrl     *gomock.Controller
	recorder *MockIFilePathMockRecorder
}

// MockIFilePathMockRecorder is the mock recorder for MockIFilePath.
type MockIFilePathMockRecorder struct {
	mock *MockIFilePath
}

// NewMockIFilePath creates a new mock instance.
func NewMockIFilePath(ctrl *gomock.Controller) *MockIFilePath {
	mock := &MockIFilePath{ctrl: ctrl}
	mock.recorder = &MockIFilePathMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIFilePath) EXPECT() *MockIFilePathMockRecorder {
	return m.recorder
}

// Getwd mocks base method.
func (m *MockIFilePath) Getwd() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Getwd")
	ret0, _ := ret[0].(string)
	return ret0
}

// Getwd indicates an expected call of Getwd.
func (mr *MockIFilePathMockRecorder) Getwd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Getwd", reflect.TypeOf((*MockIFilePath)(nil).Getwd))
}

// Join mocks base method.
func (m *MockIFilePath) Join(paths ...string) string {
	m.ctrl.T.Helper()
	varargs := []interface{}{}
	for _, a := range paths {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Join", varargs...)
	ret0, _ := ret[0].(string)
	return ret0
}

// Join indicates an expected call of Join.
func (mr *MockIFilePathMockRecorder) Join(paths ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Join", reflect.TypeOf((*MockIFilePath)(nil).Join), paths...)
}
