// Code generated by MockGen. DO NOT EDIT.
// Source: contract\i-user-service.go

// Package contract is a generated GoMock package.
package contract

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockIUserService is a mock of IUserService interface
type MockIUserService struct {
	ctrl     *gomock.Controller
	recorder *MockIUserServiceMockRecorder
}

// MockIUserServiceMockRecorder is the mock recorder for MockIUserService
type MockIUserServiceMockRecorder struct {
	mock *MockIUserService
}

// NewMockIUserService creates a new mock instance
func NewMockIUserService(ctrl *gomock.Controller) *MockIUserService {
	mock := &MockIUserService{ctrl: ctrl}
	mock.recorder = &MockIUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIUserService) EXPECT() *MockIUserServiceMockRecorder {
	return m.recorder
}

// GetRandSeedService mocks base method
func (m *MockIUserService) GetRandSeedService(arg0 string) IUserRandSeedService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandSeedService", arg0)
	ret0, _ := ret[0].(IUserRandSeedService)
	return ret0
}

// GetRandSeedService indicates an expected call of GetRandSeedService
func (mr *MockIUserServiceMockRecorder) GetRandSeedService(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandSeedService", reflect.TypeOf((*MockIUserService)(nil).GetRandSeedService), arg0)
}

// GetRewardService mocks base method
func (m *MockIUserService) GetRewardService() IUserRewardService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRewardService")
	ret0, _ := ret[0].(IUserRewardService)
	return ret0
}

// GetRewardService indicates an expected call of GetRewardService
func (mr *MockIUserServiceMockRecorder) GetRewardService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRewardService", reflect.TypeOf((*MockIUserService)(nil).GetRewardService))
}

// GetValueService mocks base method
func (m *MockIUserService) GetValueService() IValueService {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueService")
	ret0, _ := ret[0].(IValueService)
	return ret0
}

// GetValueService indicates an expected call of GetValueService
func (mr *MockIUserServiceMockRecorder) GetValueService() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueService", reflect.TypeOf((*MockIUserService)(nil).GetValueService))
}
