// Code generated by MockGen. DO NOT EDIT.
// Source: model\contract\i-value-condition.go

// Package contract is a generated GoMock package.
package contract

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockIValueCondition is a mock of IValueCondition interface.
type MockIValueCondition struct {
	ctrl     *gomock.Controller
	recorder *MockIValueConditionMockRecorder
}

// MockIValueConditionMockRecorder is the mock recorder for MockIValueCondition.
type MockIValueConditionMockRecorder struct {
	mock *MockIValueCondition
}

// NewMockIValueCondition creates a new mock instance.
func NewMockIValueCondition(ctrl *gomock.Controller) *MockIValueCondition {
	mock := &MockIValueCondition{ctrl: ctrl}
	mock.recorder = &MockIValueConditionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIValueCondition) EXPECT() *MockIValueConditionMockRecorder {
	return m.recorder
}

// GetCount mocks base method.
func (m *MockIValueCondition) GetCount() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCount")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetCount indicates an expected call of GetCount.
func (mr *MockIValueConditionMockRecorder) GetCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCount", reflect.TypeOf((*MockIValueCondition)(nil).GetCount))
}

// GetOp mocks base method.
func (m *MockIValueCondition) GetOp() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOp")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetOp indicates an expected call of GetOp.
func (mr *MockIValueConditionMockRecorder) GetOp() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOp", reflect.TypeOf((*MockIValueCondition)(nil).GetOp))
}

// GetValueType mocks base method.
func (m *MockIValueCondition) GetValueType() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetValueType")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetValueType indicates an expected call of GetValueType.
func (mr *MockIValueConditionMockRecorder) GetValueType() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetValueType", reflect.TypeOf((*MockIValueCondition)(nil).GetValueType))
}
